- alias: Turn on WC light and fan when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.4a60a2
    to: 'on'
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: 
        - switch.4cdf41
        - switch.4ce50c 
  - service: timer.start
    data:
      entity_id: timer.wc

- alias: Turn off WC 10 minutes after last movement
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.wc
  action:
    service: homeassistant.turn_off
    data:
      entity_id: 
        - switch.4cdf41
        - switch.4ce50c 


- alias: Beckett Remote Light On
  trigger:
    platform: event
    event_type: insteon.button_on
    event_data:
      address: 3eba98
  condition:
    - condition: state
      entity_id: light.becketts_room
      state: 'off'
  action:
    service: light.turn_on
    entity_id: light.becketts_room

- alias: Beckett Remote Light Off
  trigger:
    platform: event
    event_type: insteon.button_off
    event_data:
      address: 3eba98
  condition:
    - condition: state
      entity_id: light.becketts_room
      state: 'on'
  action:
    service: light.turn_off
    entity_id: light.becketts_room

- alias: Low battery front door alert
  trigger:
    platform: numeric_state
    entity_id: sensor.front_door_battery
    below: '26'
  action:
    - service: notify.notify
      data:
        title: "LOW BATTERY"
        message: "Replace front door lock battery"
        data:
          push:
            badge: 0
