- alias: Turn on WC light and fan when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.wc_motion
    to: 'on'
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: 
        - light.wc_overhead
        - switch.wc_fan 
  - service: timer.start
    data:
      entity_id: timer.wc

- alias: Turn off WC 10 minutes after last movement
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.wc
  action:
    service: homeassistant.turn_off
    data:
      entity_id: 
        - light.wc_overhead
        - switch.wc_fan 

- alias: Low battery front door alert
  trigger:
    platform: numeric_state
    entity_id: sensor.front_door_battery
    below: '26'
  action:
    - service: notify.notify
      data:
        title: "LOW BATTERY"
        message: "Replace front door lock battery"
        data:
          push:
            badge: 0

- alias: Sunset Lights
  trigger:
    platform: sun
    event: sunset
    offset: "00:00:00"
  condition:
    condition: state
    entity_id: group.household
    state: 'home'
  action:
    service: homeassistant.turn_on
    entity_id: light.living_room

- alias: "Lights when coming home"
  trigger:
    platform: state
    entity_id: group.household
    from: 'away'
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
      - condition: state
        entity_id: light.living_room
        state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: light.living_room

- alias : Master fan automation
  trigger:
  - platform: numeric_state
    entity_id: sensor.master_temp
    value_template: '{{ sensor.master_temp - sensor.outside_temp }}'
    above: 10
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
      - condition: state    
        entity_id: group.household
        state: 'home'
      - condition: numeric_state
        entity_id: sensor.master_temp
        above: 68
  action:
    service: homeassistant.turn_on
    entity_id: switch.master_fan

- alias: Master fan morning off
  trigger:
    platform: time
    at: '06:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.master_fan

#- alias: TV trigger movie scene
#  trigger:
#    platform: state
#    entity_id: media_player.living_room_apple_tv
#    from: 'idle'
#    to: 'playing'
#  condition: 
#    condition: and
#    conditions:
#      - condition: state
#        entity_id: light.living_room
#        state: 'on'
#      - condition: state
#        entity_id: sun.sun
#        state: 'below_horizon'
#  action:
#    service: scene.turn_on
#    entity_id: scene.movie
