- alias: Turn on WC light and fan when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.4a60a2
    to: 'on'
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: 
        - switch.4cdf41
        - switch.4ce50c 
  - service: timer.start
    data:
      entity_id: timer.wc

- alias: Turn off WC 10 minutes after last movement
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.wc
  action:
    service: homeassistant.turn_off
    data:
      entity_id: 
        - switch.4cdf41
        - switch.4ce50c 


- alias: Beckett Remote Light On
  trigger:
    platform: event
    event_type: insteon.button_on
    event_data:
      address: 3eba98
  condition:
    - condition: state
      entity_id: light.becketts_room
      state: 'off'
  action:
    service: light.turn_on
    entity_id: light.becketts_room

- alias: Beckett Remote Light Off
  trigger:
    platform: event
    event_type: insteon.button_off
    event_data:
      address: 3eba98
  condition:
    - condition: state
      entity_id: light.becketts_room
      state: 'on'
  action:
    service: light.turn_off
    entity_id: light.becketts_room

- alias: Low battery front door alert
  trigger:
    platform: numeric_state
    entity_id: sensor.front_door_battery
    below: '26'
  action:
    - service: notify.notify
      data:
        title: "LOW BATTERY"
        message: "Replace front door lock battery"
        data:
          push:
            badge: 0

#- alias: TV trigger movie scene
#  trigger:
#    platform: state
#    entity_id: media_player.samsung_tv_remote
#    from: 'off'
#    to: 'on'
#  condition: 
#    - condition: state
#      entity_id: light.3bc2f9
#      state: 'on'
#    - condition: sun
#      after: sunset 
#  action:
#    service: scene.turn_on
#    entity_id: scene.movie

# When we detect power being drawn from the dishwasher,
# mark the dishwasher as using power

- alias: Set dishwasher active when power detected
  trigger:
    - platform: numeric_state
      entity_id: sensor.aeotec_smart_energy_switch_power_16_8
      above: 10
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Dirty
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Clean
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Drying
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Running

# When the power level drops below 10, and the Dishwasher is set to
# the 'Running' state, mark the Dishwasher as Finished

- alias: Set dishwasher drying when power drops
  trigger:
    - platform: numeric_state
      entity_id: sensor.aeotec_smart_energy_switch_power_16_8
      below: 10
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Running
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Drying

# Once the dishwasher status has been 'Drying' for 30 minutes, mark the
# dishwasher as clean

- alias: Set dishwasher clean
  trigger:
    - platform: state
      entity_id: input_select.dishwasher_status
      to: Drying
      for:
        minutes: 15
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Drying
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Clean

# When the power drops and the dishwasher is Clean or Drying, someone has
# turned the Dishwasher off and emptied it. We should do this when the state
# of the Dishwasher is clean or Finishing, just incase someone opens the
# Dishwasher before the 30 minute timeout has been reached.

- alias: Set Dishwasher dirty when power off
  trigger:
    - platform: numeric_state
      entity_id: sensor.aeotec_smart_energy_switch_power_16_8
      below: 1
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.aeotec_smart_energy_switch_power_16_8
        below: 1
      - condition: or
        conditions:
        - condition: state
          entity_id: input_select.dishwasher_status
          state: Clean
        - condition: state
          entity_id: input_select.dishwasher_status
          state: Drying
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Dirty