- alias: Turn on WC light and fan when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.wc_motion
    to: 'on'
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: 
        - light.wc_overhead
        - switch.wc_fan 
  - service: timer.start
    data:
      entity_id: timer.wc

- alias: Turn off WC 10 minutes after last movement
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.wc
  action:
    service: homeassistant.turn_off
    data:
      entity_id: 
        - light.wc_overhead
        - switch.wc_fan 

- alias: Low battery front door alert
  trigger:
    platform: numeric_state
    entity_id: sensor.front_door_battery
    below: '26'
  action:
    - service: notify.notify
      data:
        title: "LOW BATTERY"
        message: "Replace front door lock battery"
        data:
          push:
            badge: 0

#- alias: TV trigger movie scene
#  trigger:
#    platform: state
#    entity_id: media_player.samsung_tv_remote
#    from: 'off'
#    to: 'on'
#  condition: 
#    - condition: state
#      entity_id: light.3bc2f9
#      state: 'on'
#    - condition: sun
#      after: sunset 
#  action:
#    service: scene.turn_on
#    entity_id: scene.movie
