homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

default_config:

recorder:
  purge_keep_days: 5
  db_url: mysql://hass:random4171261@core-mariadb/homeassistant?charset=utf8

discovery:
hassio:

lovelace:
  mode: storage
  # Add yaml dashboards
  dashboards:
    lovelace-soft:
      mode: yaml
      title: Soft
      icon: mdi:script
      show_in_sidebar: true
      filename: ui-lovelace-soft.yaml

august:
  login_method: email
  username: !secret august_username
  password: !secret august_password

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: chamberlain

lutron:
  host: 192.168.1.237
  username: !secret lutron_username
  password: !secret lutron_password

#sense:
#  email: !secret sense_username
#  password: !secret sense_password

binary_sensor:
  - platform: workday
    country: US
  - platform: template
    sensors:
      wine_ac_on:
        friendly_name: "Wine AC Running"
        value_template:  "{{ states('sensor.wine_ac_electrical_measurement')|float > 5 }}"

timer:
  front_door_lock:
    duration: '00:03:00'

input_boolean:
  party_mode:
    name: Party Mode
    initial: off
  vacation_mode:
    name: Vacation Mode
    icon: mdi:beach
    initial: off

input_datetime:
  only_time:
    name: Wakup Time
    has_date: false
    has_time: true

weather:
  - platform: darksky
    api_key: !secret darksky

frontend:
  themes: !include_dir_merge_named themes

# badnest:
#   issue_token: !secret nest_issue_token
#   cookie: !secret nest_cookie
#   region: us

# climate:
#   - platform: badnest
#     scan_interval: 30

sensor:
  - platform: time_date
    display_options:
      - 'time'

  - platform: template
    sensors: 
      ups_power:
        friendly_name: "UPS Power Usage"
        unit_of_measurement: 'W'
        value_template: "{{ state_attr('switch.garage_ups', 'current_power_w') }}"

  # - platform: badnest
#  - platform: xiaomi_miio
#    name: Xiaomi Air Quality Monitor
#    host: 192.168.1.49
#    token: !secret airmonitor

yeelight:
  devices:
    192.168.1.244:
      name: 'Desk Lamp'
      
# media_player:
#   - platform: onkyo
#     host: 192.168.1.12
#     name: lr_receiver

camera:
  - platform: generic
    name: "Garage Camera"
    still_image_url: http://192.168.1.195/snap.jpg
    stream_source: rtsp://192.168.1.1:7447/jX5dDRotdjxj5RDk

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influx_password
  max_retries: 3
  default_measurement: state


plant:
  master_plant:
    sensors:
      moisture: sensor.master_miflora_moisture
      battery: sensor.master_miflora_battery_level
      temperature: sensor.master_miflora_temperature
      conductivity: sensor.master_miflora_soil_conductivity
      brightness: sensor.master_miflora_illuminance
    min_moisture: 20
    max_moisture: 60
    min_battery: 17
    min_conductivity: 300
    max_conductivity: 3500
    min_temperature: 15

group: !include groups.yaml
scene: !include_dir_list scenes
automation: !include_dir_merge_list automation
script: !include scripts.yaml
