homeassistant:
  name: Home
  latitude: 37.7595
  longitude: -122.4367
  elevation: 0
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  customize_glob:
    "binary_sensor.*":
      hidden: true
    "sensor.*":
      hidden: true

default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

discovery:

sensor:
  - platform: yr

#tts:
#  - platform: google_translate

nest:
  client_id: fccdf871-403c-4a4f-8a88-275b75b2aa07
  client_secret: !secret nest_client_secret

august:
  login_method: email
  username: !secret august_username
  password: !secret august_password

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: chamberlain

lutron:
  host: 192.168.1.181
  username: !secret lutron_username
  password: !secret lutron_password

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include_dir_list scenes