homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

frontend:
config:
updater:
  include_used_components: true
# discovery:
conversation:
history:
logbook:
map:
sun:
ios:
influxdb:
logger:
  default: critical

wemo:
  static:
    - 192.168.1.225
    - 192.168.1.238

http:
  api_password: !secret api_password
  base_url: https://teich.network:8123
  ssl_certificate: /certificates/fullchain.pem 
  ssl_key: /certificates/privkey.pem

tts:
  - platform: google

mqtt:
  broker: localhost

media_player:
  - platform: samsungtv
    host: 192.168.1.208
    port: 8001
    mac: 64:1C:B0:7D:0C:1E

august:
  login_method: email
  username: oren@teich.net
  password: !secret august_password

timer:
  wc:
    duration: '00:10:00'

cover:
  - platform: myq
    username: oren@teich.net
    password: !secret myq_password
    type: chamberlain

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  
weather:
  - platform: darksky
    api_key: !secret darksky_api_key

input_select:
  dishwasher_status:
    name: Dishwasher Status
    options:
      - Dirty
      - Running
      - Drying
      - Clean
    initial: Dirty
  washing_machine_status:
    name: Washing Machine Status
    options:
      - Idle
      - Running
      - Finishing
      - Clean
    initial: Idle

panel_iframe:
  grafana:
    title: 'Grafana'
    url: 'http://toodle.local:3000'
    icon: mdi:chart-areaspline

apple_tv:
  - name: Living Room Apple TV
    host: 192.168.1.236
    login_id: !secret atv_login_id
    credentials: !secret atv_credentials

device_tracker:
  - platform: unifi
    host: 192.168.1.100
    username: !secret unifi_user
    password: !secret unifi_password
    verify_ssl: false   

homekit: !include homekit.yaml
cloud: !include cloud.yaml
automation: !include automations.yaml
light: !include lights.yaml
switch: !include switches.yaml
group: !include groups.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
scene: !include scene.yaml

binary_sensor:
  - platform: mqtt
    name: "WC Motion"
    state_topic: 'insteon/4a.60.a2/state'
    device_class: 'motion'

  - platform: mqtt
    name: "WC battery"
    state_topic: 'insteon/4a.60.a2/low_battery'
    device_class: 'battery'
