homeassistant:
  # name: Home
  # latitude: !secret lat
  # longitude: !secret long
  # elevation: 0
  # unit_system: imperial
  # time_zone: America/Los_Angeles
  customize: !include customize.yaml
  customize_glob:
    "binary_sensor.*":
      hidden: true
    "binary_sensor.closet*":
      hidden: false
    "sensor.*":
      hidden: true

default_config:

recorder:
  purge_keep_days: 5
  purge_interval: 1
  db_url: mysql://homeassistant:homeassistant@192.168.1.216:3306/homeassistant?charset=utf8

discovery:
hassio:

nest:
 client_id: !secret nest_client_id
 client_secret: !secret nest_client_secret

august:
  login_method: email
  username: !secret august_username
  password: !secret august_password

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: chamberlain

lutron:
  host: 192.168.1.181
  username: !secret lutron_username
  password: !secret lutron_password

#sense:
#  email: !secret sense_username
#  password: !secret sense_password

binary_sensor:
  - platform: workday
    country: US

timer:
  front_door_lock:
    duration: '00:03:00'

input_boolean:
  party_mode:
    name: Party Mode
    initial: off
  vacation_mode:
    name: Vacation Mode
    icon: mdi:beach
    initial: off

<<<<<<< HEAD
# wemo:
#   discovery: false
#   static:
#     - 192.168.1.90

=======
input_datetime:
  only_time:
    name: Wakup Time
    has_date: false
    has_time: true

wemo:
  discovery: true
  # static:
    # - 192.168.1.90

sensor:
  - platform: time_date
    display_options:
      - 'time'

>>>>>>> master
#sensor:
#  - platform: xiaomi_miio
#    name: Xiaomi Air Quality Monitor
#    host: 192.168.1.49
#    token: !secret airmonitor
<<<<<<< HEAD
=======

weather:
  - platform: darksky
    api_key: !secret darksky
>>>>>>> master

group: !include groups.yaml
script: !include scripts.yaml
scene: !include_dir_list scenes
automation: !include_dir_merge_list automation
homekit: !include homekit.yaml
