- platform: template
  sensors:
    front_door_battery:
      friendly_name: "Front Door Lock Battery %"
      entity_id: lock.front_door
      value_template: "{{ states.lock.front_door.attributes.battery_level }}"
    master_temp:
      value_template: '{{ states.climate.master.attributes.current_temperature }}'
      friendly_name: 'Master Temperature'
      unit_of_measurement: 'Degrees'
    outside_temp:
      value_template: '{{ states.weather.dark_sky.attributes.temperature }}'
      friendly_name: 'Outside temperature'
      unit_of_measurement: 'Degrees'
# - platform: speedtest
#   monitored_conditions:
#     - ping
#     - download
#     - upload