title: Home
views:
  - path: default_view
    title: default_view
    badges: []
    cards:
      - type: entities
        entities:
          - scene.bedtime
          - scene.morning
          - scene.sleep
          - scene.night_fan
        title: Scenes
        show_header_toggle: false
      - type: entities
        entities:
          - person.oren_teich
          - person.olivia_teich
        title: Family People
        show_header_toggle: false
      - type: entities
        entities:
          - cover.30th_garage_door
          - input_boolean.party_mode
          - input_boolean.vacation_mode
          - input_datetime.only_time
        title: Main Controls
        show_header_toggle: false
    icon: 'mdi:home'
  - path: downstairs
    title: Downstairs
    badges: []
    cards:
      - type: entities
        entities:
          - light.entry_hall_entry_lamp
          - light.entry_hall_entry_led_cove
          - light.entry_hall_stair_down_enytry_lights
          - lock.front_door
        title: Entry
        show_header_toggle: true
      - type: entities
        entities:
          - light.guest_bath_bath_3_cans
          - light.guest_bath_bath_3_penndant
          - light.guest_bath_bath_3_towel_warmer
          - light.guest_bath_guest_bath_fan
          - light.guest_bed_guest_bed_cans
        title: Guest Bedroom
        show_header_toggle: true
      - type: entities
        entities:
          - light.wine_cellar_wine_cellar_cans
          - light.wine_cellar_wine_cellar_pendant
        title: Cellar
        show_header_toggle: true
      - type: entities
        entities:
          - cover.30th_garage_door
        title: Garage
        show_header_toggle: false
      - type: entities
        entities:
          - light.back_deck_exterior_cans
          - light.entry_hall_front_step_lights
          - light.kitchen_breakfast_nook_kitchen_exterior
          - light.living_room_stair_up_exterior_deck_can
          - light.master_bed_exterior_deck_sconce
          - light.office_stair_landing_exterior_deck_step_lights
        title: Outside
        show_header_toggle: true
  - path: main_floor
    title: Main Floor
    badges: []
    cards:
      - type: entities
        entities:
          - light.dining_room_stair_down_dining_room_art_cans
          - light.dining_room_stair_down_dining_room_lamp
          - light.dining_room_stair_down_dining_table_pendant
          - light.dining_room_stair_down_kit_to_liv_room_hall_cans_a1x2
        title: Dining Room
        show_header_toggle: true
      - type: entities
        entities:
          - light.kitchen_breakfast_nook_breakfast_nook_cans
          - light.kitchen_breakfast_nook_kitchen_art_wall_powder_hall_cans
          - light.kitchen_breakfast_nook_kitchen_bar_light
          - light.kitchen_breakfast_nook_kitchen_field_cans
          - light.kitchen_breakfast_nook_kitchen_island_pendant
          - light.kitchen_breakfast_nook_kitchen_under_cab
        title: Kitchen
        show_header_toggle: true
      - type: entities
        entities:
          - light.dining_room_stair_down_top_of_stair_sconce_nook_lights
        title: landing
        show_header_toggle: true
      - type: entities
        entities:
          - light.laundry_room_laundry_fan
          - light.laundry_room_laundry_room
          - light.powder_room_powder_fan
          - light.powder_room_powder_room_pendant
          - light.powder_room_powder_room_can
          - switch.hot_water_recirc
        title: Laundry & Powder Room
        show_header_toggle: true
      - type: entities
        entities:
          - light.living_room_stair_up_art_wall_lights
          - light.living_room_stair_up_hall_cans_x_8
          - light.living_room_stair_up_piano_wall_stair_up_cans
          - light.living_room_stair_up_tv_wall_cans
        title: Living Room
        show_header_toggle: true
  - path: upstairs
    title: Upstairs
    badges: []
    cards:
      - type: entities
        entities:
          - light.office_stair_landing_office_cans
          - light.office_stair_landing_stair_hall_cans
        title: Office
        show_header_toggle: true
      - type: entities
        entities:
          - light.bath_2_bath_2_cans
          - light.bath_2_bath_2_fan
          - light.bath_2_bath_2_pendant
          - light.bed_2_bed_2_cans
          - light.bed_2_bed_2_closet_cans
          - light.bed_2_bed_2_lamp
          - cover.velux_window_3
        title: Beckett's Room
        show_header_toggle: true
      - type: entities
        entities:
          - cover.master_bed_bed_corner_window
          - cover.master_bed_deck_blackout
          - cover.master_bed_deck_sheer
          - cover.master_bed_tv_window_left
          - cover.master_bed_tv_window_right
          - light.master_bed_m_bed_cans
          - light.master_bed_m_bed_lamp_left
          - light.master_bed_m_bed_lamp_right
          - switch.fan
        title: Master Bedroom
        show_header_toggle: true
      - type: entities
        entities:
          - light.master_bath_closet_m_bath_cans
          - light.master_bath_closet_m_bath_fan
          - light.master_bath_closet_m_bath_pendant
          - light.master_bath_closet_m_closet_cans
          - light.master_bath_closet_m_closet_towel_warmer
          - cover.velux_window_2
        title: Master Bathroom
        show_header_toggle: true
  - path: cameras
    title: Cameras
    badges: []
    cards: []
    icon: 'mdi:camera'
  - path: sonos
    title: sonos
    badges: []
    cards:
      - type: media-control
        entity: media_player.media
      - type: media-control
        entity: media_player.kitchen
      - type: media-control
        entity: media_player.office
      - type: media-control
        entity: media_player.master_bedroom
      - type: media-control
        entity: media_player.master_bath
      - type: media-control
        entity: media_player.outside
      - type: media-control
        entity: media_player.dining_room
    icon: 'mdi:music-circle'
  - path: thermostats
    title: thermostats
    badges: []
    cards: []
    icon: 'mdi:radiator'

