esphome:
  name: closetshoes
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "spigot"
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

light:
  - platform: neopixelbus
    id: shoelights
    variant: SK6812
    pin: GPIO3
    num_leds: 240
    type: GRBW
    effects: 
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_fireworks:
    name: "Shoes Lights"

binary_sensor:
  - platform: gpio
    pin: D1
    name: "Closet LED Motion Sensor"
    device_class: motion