esphome:
  name: closetshoes
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "spigot"
  password: "1119middlefield"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

light:
  - platform: neopixelbus
    id: shoelights
    variant: SK6812
    pin: GPIO3
    num_leds: 150
    type: GRBW
    name: "Shoes Lights"
    effects:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:

  # - platform: partition
  #   name: "Shelf 1"
  #   segments:
  #     - id: shoelights
  #       from: 0
  #       to: 30
  # - platform: partition
  #   name: "Shelf 2"
  #   segments:
  #     - id: shoelights
  #       from: 61
  #       to: 93
  # - platform: partition
  #   name: "Shelf 3"
  #   segments:
  #     - id: shoelights
  #       from: 109
  #       to: 139

binary_sensor:
  - platform: gpio
    pin: D1
    name: "Closet LED Motion Sensor"
    device_class: motion