esphome:
  name: mastercloset
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "spigot"
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mastercloset Fallback Hotspot"
    password: "KuaCfKYTwMlC"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

esp32_ble_tracker:

ota:

light:
  - platform: neopixelbus
    id: shoelights
    variant: SK6812
    pin: GPIO5
    num_leds: 240
    type: GRBW
    effects: 
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_fireworks:
    name: "Shoes Lights"

binary_sensor:
  - platform: gpio
    pin: GPIO35
    name: "Closet LED Motion Sensor"
    device_class: motion

# sensor:
#   - platform: xiaomi_miflora
#     mac_address: 94:2B:FF:5C:91:61
#     temperature:
#       name: "Xiaomi MiFlora Temperature"
#     moisture:
#       name: "Xiaomi MiFlora Moisture"
#     illuminance:
#       name: "Xiaomi MiFlora Illuminance"
#     conductivity:
#       name: "Xiaomi MiFlora Soil Conductivity"
#     battery_level:
#       name: "Xiaomi MiFlora Battery Level"