homeassistant:
  customize:
    sensor.washing_machine_status:
      icon: mdi:washing-machine
    sensor.dishwasher_status:
      icon: mdi:dishwasher
    sensor.dryer_status:
      icon: mdi:washing-machine
    sensor.washing_machine_power:
      icon: mdi:flash
    sensor.dishwasher_power:
      icon: mdi:flash
    sensor.dryer_power:
      icon: mdi:flash 

#############################################################
#                 Insteon Devices
#############################################################
binary_sensor:
  - platform: mqtt
    name: "Washing Machine Door"
    state_topic: 'insteon/4e.38.58/state'
    device_class: 'door'
    icon: mdi:glassdoor

  - platform: mqtt
    name: "Washing Machine Door Low Battery"
    state_topic: 'insteon/4e.38.58/low_battery'
    device_class: 'battery'

#############################################################
#                 Input Selections 
#############################################################
input_select:
  dishwasher_status:
    name: Dishwasher Status
    options:
      - Dirty
      - Running
      - Drying
      - Clean
    initial: Dirty
  washing_machine_status:
    name: Washing Machine Status
    options:
      - Idle
      - Running
      - Finishing
      - Clean
    initial: Idle
  dryer_status:
    name: Dryer Status
    options:
      - Idle
      - Running
      - Tumbling
      - Done
    initial: Idle

#############################################################
#                 Sensors
#############################################################

sensor:
  - platform: template
    sensors:
      washing_machine_status:
        value_template: '{{ states.input_select.washing_machine_status.state}}'
        friendly_name: 'Washing Machine Status'
      washing_machine_power:
        value_template: '{{ states.switch.washing_machine.attributes.current_power_w }}'
        friendly_name: 'Washing Machine Power'
        unit_of_measurement: 'W'

      dishwasher_status:
        value_template: '{{ states.input_select.dishwasher_status.state}}'
        friendly_name: 'Dishwasher Status'
      dishwasher_power:
        value_template: '{{ states.switch.dishwasher.attributes.current_power_w }}'
        friendly_name: 'Dishwasher Power'
        unit_of_measurement: 'W'

      dryer_status:
        value_template: '{{ states.input_select.dryer_status.state}}'
        friendly_name: 'Dryer Status'
      dryer_power:
        value_template: '{{ states.switch.dryer.attributes.current_power_w }}'
        friendly_name: 'Dryer Power'
        unit_of_measurement: 'W'


#############################################################
#                 Group
#############################################################

group:
  washing_machine:
    name: Washing Machine
    entities:
      - sensor.washing_machine_status
      - switch.washing_machine
      - sensor.washing_machine_power
      - binary_sensor.washing_machine_door

  dishwasher:
    name: Dishwasher
    entities:
      - sensor.dishwasher_status
      - switch.dishwasher
      - sensor.dishwasher_power

  dryer:
    name: Dryer
    entities:
      - sensor.dryer_status
      - switch.dryer
      - sensor.dryer_power

  kitchen:
    name: Appliances
    view: yes
    entities:
      - group.washing_machine
      - group.dishwasher
      - group.dryer
#############################################################
#                 Automations
#############################################################

## DISHWASHER

automation:
  - alias: "Set dishwasher active when power detected"
    trigger:
      - platform: numeric_state
        entity_id: sensor.dishwasher_power
        above: 10
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dishwasher_status
          option: Running

  - alias: Set dishwasher drying when power drops
    trigger:
      - platform: numeric_state
        entity_id: sensor.dishwasher_power
        below: 10
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.dishwasher_status
          state: Running
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dishwasher_status
          option: Drying

  - alias: Set dishwasher clean
    trigger:
      - platform: state
        entity_id: input_select.dishwasher_status
        to: Drying
        for:
          minutes: 40
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.dishwasher_status
          state: Drying
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dishwasher_status
          option: Clean


## WAshing Machine

  - alias: "Set washing machine active when power detected"
    trigger:
      - platform: numeric_state
        entity_id: sensor.washing_machine_power
        above: 10
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Running


  - alias: Set washing machine finishing when power drops
    trigger:
      - platform: numeric_state
        entity_id: sensor.washing_machine_power
        below: 10
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Running
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Finishing

  - alias: Set washing machine done
    trigger:
      - platform: state
        entity_id: input_select.washing_machine_status
        to: Finishing
        for:
          minutes: 8
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Finishing
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Clean

  # When we open the washing machine door, reset the status back to
  # idle, so we don't spam people that the washing machine has 
  # finished, and someone has already emptied it
  - alias: Set washing machine dirty when door opens
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_door
        to: 'Open'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Clean
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Idle

  - alias: Send alert when washing machine is finished
    trigger:
      - platform: state
        entity_id: sensor.washing_machine_status
        to: Clean
        for:
          minutes: 1
      - platform: state
        entity_id: device_tracker.oren
        to: 'home'
        for:
          minutes: 2
      - platform: state
        entity_id: device_tracker.olivia
        to: 'home'
        for:
          minutes: 2
      - platform: time
        after: '08:45:00'
    condition:
      condition: and
      conditions:
        - condition: time
          before: '22:30:00'
          after: '08:30:00'
        - condition: state
          entity_id: group.people
          state: 'home'
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Clean
        - condition: template
          value_template: >
            {% if states.automation.send_alert_when_washing_machine_is_finished.last_triggered is not none %}
              {% if as_timestamp(now()) | int   -  as_timestamp(states.automation.send_alert_when_washing_machine_is_finished.attributes.last_triggered) | int > 1800 %} true {% else %} false
              {% endif %}
            {% else %}
            false
            {% endif %}
    action:
      - service_template: >
          {% if (is_state('device_tracker.oren', 'home')) and (is_state('device_tracker.olivia', 'home'))  %}
            notify.oren_and_olivia
          {% elif is_state('device_tracker.oren', 'home') %}
            notify.oren
          {% elif is_state('device_tracker.olivia', 'home') %}
            notify.olivia
          {% endif %}
        data:
          message: 'Hey, the washing machine has finished and is ready to be emptied'
          title: 'Washing Machine'


  - alias: "Set dryer active when power detected"
    trigger:
      - platform: numeric_state
        entity_id: sensor.dryer_power
        above: 10
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dryer_status
          option: Running