switch:
  - platform: mqtt
    state_topic: 'insteon/4c.df.41/state'
    command_topic: 'insteon/4c.df.41/set'
    name: 'WC Fan'
    icon: mdi:fan

  - platform: mqtt
    state_topic: 'insteon/28.34.fc/state'
    command_topic: 'insteon/28.34.fc/set'
    name: 'Master Fan'
    icon: mdi:fan

  - platform: mqtt
    state_topic: 'insteon/3e.ba.98/state'
    command_topic: 'insteon/3e.ba.98/set'
    name: 'Beckett Remote'

  - platform: mqtt
    state_topic: 'insteon/4e.43.95/state'
    command_topic: 'insteon/4e.43.95/set'
    name: 'Backyard Fountain'
    icon: mdi:water

light:
  - platform: mqtt
    schema: json
    name: "Living Room"
    state_topic: "insteon/3b.c2.f9/state"
    command_topic: "insteon/3b.c2.f9/level"
    brightness: true

  - platform: mqtt
    schema: json
    name: 'Stairs'
    state_topic: "insteon/3c.f3.e7/state"
    command_topic: "insteon/3c.f3.e7/level"
    brightness: true

  - platform: mqtt
    schema: json
    name: 'Thunder'
    state_topic: "insteon/35.85.7c/state"
    command_topic: "insteon/35.85.7c/level"
    brightness: true

  - platform: mqtt
    schema: json
    name: 'Kitchen Island'
    state_topic: "insteon/3b.af.d3/state"
    command_topic: "insteon/3b.af.d3/level"
    brightness: true

  - platform: mqtt
    schema: json
    name: 'Downstairs Hallway'
    state_topic: "insteon/3b.b4.d4/state"
    command_topic: "insteon/3b.b4.d4/level"
    brightness: true
    unique_id: 'down_hall'

  - platform: mqtt
    schema: json
    name: 'Master Overhead'
    state_topic: "insteon/3b.c0.fd/state"
    command_topic: "insteon/3b.c0.fd/level"
    brightness: true

  - platform: mqtt
    schema: json
    name: 'Kitchen Overhead'
    state_topic: "insteon/3b.c6.b4/state"
    command_topic: "insteon/3b.c6.b4/level"
    brightness: true

  - platform: mqtt
    schema: json
    name: 'Lilies'
    state_topic: "insteon/3b.cb.8b/state"
    command_topic: "insteon/3b.cb.8b/level"
    brightness: true

  - platform: mqtt
    schema: json
    name: 'Guest Bathroom'
    state_topic: "insteon/3c.de.52/state"
    command_topic: "insteon/3c.de.52/level"
    brightness: true
    unique_id: 'down_guest_bath'

  - platform: mqtt
    schema: json
    name: 'Beckett Overhead'
    state_topic: "insteon/3d.0e.6a/state"
    command_topic: "insteon/3d.0e.6a/level"
    brightness: true

  - platform: mqtt
    schema: json
    name: 'Bamboo Overhead'
    state_topic: "insteon/3d.16.4c/state"
    command_topic: "insteon/3d.16.4c/level"
    brightness: true

  - platform: mqtt
    state_topic: 'insteon/38.55.f7/state'
    command_topic: 'insteon/38.55.f7/set'
    name: 'Upstairs Patio Seat'

  - platform: mqtt
    state_topic: 'insteon/38.56.4e/state'
    command_topic: 'insteon/38.56.4e/set'
    name: 'Kitchen Cabinets'

  - platform: mqtt
    state_topic: 'insteon/4c.e5.0c/state'
    command_topic: 'insteon/4c.e5.0c/set'
    name: 'WC Overhead'

  - platform: mqtt
    state_topic: 'insteon/4c.a2.7b/state'
    command_topic: 'insteon/4c.a2.7b/set'
    name: 'Backyard'

  - platform: mqtt
    state_topic: 'insteon/3d.23.c2/state'
    command_topic: 'insteon/3d.23.c2/set'
    name: 'Master Closet'

  - platform: mqtt
    state_topic: 'insteon/3d.23.d4/state'
    command_topic: 'insteon/3d.23.d4/set'
    name: 'Beckett Bathroom Vanity'
    
  - platform: mqtt
    state_topic: 'insteon/3d.28.3c/state'
    command_topic: 'insteon/3d.28.3c/set'
    name: 'Laundry'

  # - platform: mqtt
  #   state_topic: 'insteon/3d.2a.c9/state'
  #   command_topic: 'insteon/3d.2a.c9/set'
  #   name: 'UNUSED'

  - platform: mqtt
    state_topic: 'insteon/3d.2a.f3/state'
    command_topic: 'insteon/3d.2a.f3/set'
    name: 'Downstairs Side Outside'

  - platform: mqtt
    state_topic: 'insteon/3d.2d.32/state'
    command_topic: 'insteon/3d.2d.32/set'
    name: 'Upstairs Patio Door'

  - platform: mqtt
    schema: json
    name: 'Master Bathroom'
    state_topic: "insteon/49.51.52/state"
    command_topic: "insteon/49.51.52/level"
    brightness: true

  - platform: mqtt
    state_topic: 'insteon/4c.e4.cf/state'
    command_topic: 'insteon/4c.e4.cf/set'
    name: 'Front Steps'

binary_sensor:
  - platform: mqtt
    name: "WC Motion"
    state_topic: 'insteon/4a.60.a2/state'
    device_class: 'motion'

  - platform: mqtt
    name: "WC battery"
    state_topic: 'insteon/4a.60.a2/low_battery'
    device_class: 'battery'

automation:
  - alias: "Dim bedroom LED brightness at night"
    trigger:
      platform:  time
      at: '22:00:00'
    action:
      - service: mqtt.publish
        data_template:
          topic: 'insteon/command/3b.c0.fd'
          payload: { \"cmd\" : \"set_flags\", \"backlight\" : \"0x15\" }
      - service: mqtt.publish
        data_template:
          topic: 'insteon/command/3d.23.c2'
          payload: { \"cmd\" : \"set_flags\", \"backlight\" : \"0x15\" }

  - alias: 'Make bedroom LED brightness full in AM'
    trigger:
      platform:  time
      at: '06:00:00'
    action:
      - service: mqtt.publish
        data_template:
          topic: 'insteon/command/3b.c0.fd'
          payload: { \"cmd\" : \"set_flags\", \"backlight\" : \"0xff\" }
      - service: mqtt.publish
        data_template:
          topic: 'insteon/command/3d.23.c2'
          payload: { \"cmd\" : \"set_flags\", \"backlight\" : \"0xff\" }
