name: Check Home Assistant config
on: [push]

jobs:
  check:
 
    runs-on: ubuntu-latest
    container:
      image: homeassistant/amd64-homeassistant
    steps:
    - uses: actions/checkout@v1
    - name: Copy Secrets
      run: cp secrets_ci.yaml secrets.yaml
    - name: Build the Docker image
      run: hass --script check_config -c .
